name: Daily DESCO Monitor

on:
  schedule:
    - cron: '50 11 * * *' # runs daily at 4:01 PM Asia/Dhaka (10:01 UTC)
  # workflow_dispatch: # allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests urllib3

      - name: Run DESCO script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python meter_bill_daily_update_local_immidiate.py
